### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by ghost**
Updated the German translation after a long time, I hope I translated everything!

### CODE REVIEW

**Comment by JT122406** [comment]
Hey, Thanks for the help, I'm gonna wait to merge this because if possible, could you do the translations for the new spooktober update stuff as well

**Comment by ieguana** [comment]
no problem, and done! is it only the spirit roots that are new or is there some stuff still coming?

**Comment by JT122406** [comment]
@ieguana If possible can you add the rest of the new translations that were added recently and I will get this merged in for 2.2.0 Release

**Comment by ieguana** [comment]
Done!

Edit: Quick question about the Forgotten Nostalgia advancement, do you get it when you give a Pumpkin Warden a rose if I understood it correctly? Because right now, the advancement has no description, and I added one because I didn't want to leave it empty

**Comment by JT122406** [comment]
Yes, I'm adding it rn if you can translate it now

**Comment by ieguana** [comment]
Done

**Comment by JT122406** [comment]
Thanks!

**Comment by ieguana** [comment]
You're welcome!

**Comment by JT122406** [comment]
@ieguana If you are willing could you make translations for our new add-on https://github.com/Potion-Studios/All-The-Wood-Weve-Got

**Comment by ieguana** [comment]
I've made the PR on the repo!

**Comment by JT122406** [comment]
@ieguana Hey, if you are willing we have a new update coming soon with some new things that need translations, it's in the Custom-Villagers branch if you are able to PR into it!

**Pull request merged**
