### PR TITLE
Finish and Tweak German Translations

### PR DESCRIPTION
**Pull request by ghost**
Some fixes

### CODE REVIEW

**Comment by JT122406** [comment]
https://github.com/Potion-Studios/All-The-Wood-Weve-Got/pull/10

**Review by JT122406 — CHANGES_REQUESTED** [review]
Hey @ieguana I appreciate the changes.  
I pushed a commit to your branch with all the missing translations if possible could you do all of those and then I will merge this.

**Comment by ieguana** [comment]
All done!

**Review by JT122406 — APPROVED** [review]
Thanks!

**Comment by ieguana** [comment]
You're welcome!

**Comment by ieguana** [comment]
@JT122406 Hey, I've been inactive for a while, were there any new translations so I could maybe translate them? Thanks!

**Pull request merged**
