### PR TITLE
Fix multiple FOC crashes

### LINKED ISSUE #6: Incompatibility with Excessive Building (Temp Solution: Use Feature Recycler)
Booting to menu works just fine but the second I try to load a world or start a fresh one, Im greeted with nothing but black, can't see, can't move nothing.

[debug.log](https://mclo.gs/tOmTzZu)

[latest.log](https://mclo.gs/qJ5INH4)

[MineColonies: Dimensional Adventure Modpack](https://www.curseforge.com/minecraft/modpacks/minecolonies-dimensional-adventure)

Screenshot_3

MC Version: 1.20.1
Forge Version 47.3.5
BWG Version: 1.0.0-Beta-SNAPSHOT

### PR DESCRIPTION
**Pull request by Apollounknowndev**
Closes #6, #14 and #44. 

Fixes compatibility with Excessive Building, Blooming Biosphere, and Slayer's Beasts by reordering some vanilla features in the Sakura Grove and Howling Peaks.

Feature order cycle crashes with Cliff Under a Tree (#37) and William Wyther's Expanded Ecosphere (#16) are issues not on BWG's end and will be forwarded to relevant devs to fix the issue on their end.

### CODE REVIEW

**Comment by JT122406** [comment]
@Apollounknowndev Is this done as it looks like features were removed and not reordered?

**Comment by CorgiTaco** [comment]
This is not the correct way to handle this. We have these features in our biomes for good reason, removing these features takes away content from our biomes.

**Review by CorgiTaco — CHANGES_REQUESTED** [review]
Should not remove features.

**Comment by Apollounknowndev** [comment]
Howling peaks:
- `patch_grass_taiga_2` was removed because `patch_grass_taiga` is the same feature but 7 times more common.
- `brown_mushroom_taiga` was removed because `brown_mushroom_old_growth` is the same feature but 3 times more common.
- `red_mushroom_taiga` was removed because `red_mushroom_old_growth` is the same feature but 50% more common.

Sakura Grove:
- `patch_grass_badlands` was removed because `patch_grass_plain` is the same feature but 10 times more common.
- `patch_grass_badlands` was removed because `patch_grass_plain` is the same feature but 5 times more common.

**Comment by Apollounknowndev** [comment]
On top of the removals, `flower_default` in Sakura Grove was moved further down in the `vegetal_decoration` step.

**Review by JT122406 — APPROVED** [review]

**Review by JT122406 — APPROVED** [review]

**Comment by JT122406** [comment]
Did you test this? @Apollounknowndev

**Comment by JT122406** [comment]
I am now getting FOC crashes with no other mods

**Comment by Apollounknowndev** [comment]
I tested it and it worked fine
image

**Comment by JT122406** [comment]
Can you pull latest commit and try?

**Pull request merged**
